# -*- coding: utf-8 -*-
"""Local RETFound_colab.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HjLFNb9CaGKBzWJuJwTOIM4D4hT7WIeL

# **RETFound**

This is the official notebook for RETFound (*Nature* 2023).

This notebook demonstrates <font color=orange size=2>**RETFound** usage on your customise data.

Make sure to specify a GPU runtime. Click Runtime -->Change runtime type --> Hardware --> GPU and save.

Contact: [yukun.zhou.19@ucl.ac.uk] [ykzhoua@gmail.com]...

If you find this notebook useful, please star our [project on Github](https://github.com/rmaphoh/RETFound_MAE) and cite [RETFound paper](https://www.nature.com/articles/s41586-023-06555-x).

👋 Join RETFound support team by pulling requests or dropping emails to
* improve notebook in organisation, generalisation, and flexibility
* organise new CFP or OCT dataset in structure
* feedback suggestions to improve user experience
"""

# prompt: connect to local drive

from google.colab import drive
drive.mount('/content/drive')



"""## **Install dependencies**"""

# Commented out IPython magic to ensure Python compatibility.
# %%shell
# MINICONDA_INSTALLER_SCRIPT=Miniconda3-py37_4.11.0-Linux-x86_64.sh
# MINICONDA_PREFIX=/usr/local
# wget https://repo.continuum.io/miniconda/$MINICONDA_INSTALLER_SCRIPT
# chmod +x $MINICONDA_INSTALLER_SCRIPT
# ./$MINICONDA_INSTALLER_SCRIPT -b -f -p $MINICONDA_PREFIX

# Commented out IPython magic to ensure Python compatibility.
# %%shell
# eval "$(conda shell.bash hook)" # copy conda command to shell
# source /usr/local/etc/profile.d/conda.sh
# conda init
# conda create -n retfound python=3.7.5 -y
# conda activate retfound
# python --version
# pip install ipykernel
# python -m ipykernel install --user

"""## **Clone RETFound and install packages**"""

# Commented out IPython magic to ensure Python compatibility.
# %%shell
# git clone https://github.com/rmaphoh/RETFound_MAE/
# source activate retfound
# cd RETFound_MAE/
# pip install --ignore-installed certifi
# pip install -r requirement.txt

"""###Download RETFound SSL weights###"""

!gdown --id 1l62zbWUFTlp214SvK6eMwPQZAzcwoeBE

# Commented out IPython magic to ensure Python compatibility.
# %%shell
# mv RETFound_cfp_weights.pth RETFound_MAE/

"""## **Running RETFound**

###Organise your data into a directory structure (using IDRiD as an example below)###

<img src="https://drive.google.com/uc?export=view&id=1FP59R9A5OE8kQUlG-pJAFC2JgQAcwqo7" width="200px" />
"""

!gdown --id 1c6zexA705z-ANEBNXJOBsk6uCvRnzmr3

# Commented out IPython magic to ensure Python compatibility.
# %%shell
# cd RETFound_MAE

"""###Start training###

Change the nb_classes and data_path based on your data setting.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%shell
# cd RETFound_MAE
# eval "$(conda shell.bash hook)" # copy conda command to shell
# source activate retfound
# python -m torch.distributed.launch --nproc_per_node=1 --master_port=48798 main_finetune.py \
#     --batch_size 16 \
#     --world_size 1 \
#     --model vit_large_patch16 \
#     --epochs 50 \
#     --blr 5e-3 --layer_decay 0.65 \
#     --weight_decay 0.05 --drop_path 0.2 \
#     --nb_classes 3 \
#     --data_path /content/RETFound_MAE/macular \
#     --task ./finetune_macular/ \
#     --finetune ./RETFound_cfp_weights.pth \
#     --input_size 224

# Commented out IPython magic to ensure Python compatibility.
# %pwd
# %cd drive/MyDrive

!ls *.pth

"""###For evaluation only###

Change the nb_classes and data_path based on your data setting.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%shell
# eval "$(conda shell.bash hook)" # copy conda command to shell
# source activate retfound
# python -m torch.distributed.launch --nproc_per_node=1 --master_port=48798 main_finetune.py \
#     --eval --batch_size 16 \
#     --world_size 1 \
#     --model vit_large_patch16 \
#     --epochs 50 \
#     --blr 5e-3 --layer_decay 0.65 \
#     --weight_decay 0.05 --drop_path 0.2 \
#     --nb_classes 5 \
#     --data_path ./IDRiD_data/ \
#     --task ./internal_IDRiD/ \
#     --resume ./diabetic-retinopathy-weights.pth \
#     --finetune ./RETFound_cfp_weights.pth \
#     --input_size 224

# Commented out IPython magic to ensure Python compatibility.
# %cd RETFound_MAE/finetune_IDRiD/

!cp checkpoint-best.pth drive/MyDrive

!pwd